sonar.coverage.exclusions=**/*.java,**/src/main/java/**/*.java,src/main/java/**/*.java
sonar.cpd.exclusions=**/*.java,**/src/main/java/**/*.java,src/main/java/**/*.java
sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd,**/uploads/**,**/*.zip